Add verification step

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -24,6 +24,23 @@ jobs:
           pattern: hetzner-k3s-*
           merge-multiple: true
 
+      - name: Verify Expected Binaries
+        run: |
+          set -euo pipefail
+          expected_binaries=(
+            "hetzner-k3s-macos-arm64"
+            "hetzner-k3s-macos-amd64"
+            "hetzner-k3s-linux-arm64"
+            "hetzner-k3s-linux-amd64"
+          )
+          
+          for expected_binary in "${expected_binaries[@]}"; do
+            if [[ ! -f "$expected_binary" ]]; then
+              echo "Error, release requires $expected_binary to be generated by CI workflow"
+              exit 2
+            fi
+          done
+
       - name: Upload release assets
         uses: svenstaro/upload-release-action@v2
         with:
